// Generated by `npm run codegen` from api/openapi.yaml. Do not edit.

export const spaRoutes = [
  "/",
  "/all",
  "/{vendor}",
  "/{vendor}/{app}",
  "/admin/login",
  "/admin/overview",
  "/admin/events",
  "/admin/settings/site",
  "/admin/settings/proxy",
  "/admin/vendors",
  "/admin/vendors/new",
  "/admin/categories",
  "/admin/vendors/{vendor}",
  "/admin/vendors/{vendor}/settings",
  "/admin/vendors/{vendor}/apps",
  "/admin/vendors/{vendor}/apps/new",
  "/admin/vendors/{vendor}/admin-notes",
  "/admin/vendors/{vendor}/apps/{app}/settings",
  "/admin/vendors/{vendor}/apps/{app}/admin-notes",
  "/admin/vendors/{vendor}/apps/{app}/versions",
  "/admin/vendors/{vendor}/apps/{app}/cache",
  "/admin/vendors/{vendor}/apps/{app}/files"
] as const;

export const spaAllowedQuery = [
  "returnTo",
  "q",
  "state",
  "page",
  "category",
  "cleanup"
] as const;

export const spaDocuments = {
  "public": "index.html",
  "admin": "admin.html"
} as const;

export const errorCatalog = {
  "INVALID_REQUEST": {
    "status": 400,
    "retryable": false
  },
  "VALIDATION_FAILED": {
    "status": 400,
    "retryable": false
  },
  "INVALID_QUERY": {
    "status": 400,
    "retryable": false
  },
  "INVALID_CURSOR": {
    "status": 400,
    "retryable": false
  },
  "INVALID_PATH": {
    "status": 400,
    "retryable": false
  },
  "REQUEST_ORIGIN_INVALID": {
    "status": 400,
    "retryable": false
  },
  "IF_MATCH_REQUIRED": {
    "status": 400,
    "retryable": false
  },
  "CURRENT_PASSWORD_INCORRECT": {
    "status": 400,
    "retryable": false
  },
  "PASSWORD_INVALID": {
    "status": 400,
    "retryable": false
  },
  "PROXY_REDACTED_MISMATCH": {
    "status": 400,
    "retryable": false
  },
  "ICON_INVALID": {
    "status": 400,
    "retryable": false
  },
  "PACKAGE_INVALID": {
    "status": 400,
    "retryable": false
  },
  "INSTRUCTIONS_TRUST_REQUIRED": {
    "status": 400,
    "retryable": false
  },
  "AUTH_REQUIRED": {
    "status": 401,
    "retryable": false
  },
  "LOGIN_FAILED": {
    "status": 401,
    "retryable": false
  },
  "ORIGIN_REJECTED": {
    "status": 403,
    "retryable": false
  },
  "CSRF_REJECTED": {
    "status": 403,
    "retryable": false
  },
  "NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "VENDOR_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "APPLICATION_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "CATEGORY_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "FILE_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "SOURCE_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "PREVIEW_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "JOB_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "TRANSFER_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "CACHE_ENTRY_NOT_FOUND": {
    "status": 404,
    "retryable": false
  },
  "CAPABILITY_UNSUPPORTED": {
    "status": 404,
    "retryable": false
  },
  "METHOD_NOT_ALLOWED": {
    "status": 405,
    "retryable": false
  },
  "REVISION_CONFLICT": {
    "status": 409,
    "retryable": false
  },
  "ALREADY_EXISTS": {
    "status": 409,
    "retryable": false
  },
  "VENDOR_NOT_EMPTY": {
    "status": 409,
    "retryable": false
  },
  "BUILTIN_PROTECTED": {
    "status": 409,
    "retryable": false
  },
  "ENTITY_DELETED": {
    "status": 409,
    "retryable": false
  },
  "APPLICATION_DELETE_PENDING": {
    "status": 409,
    "retryable": true
  },
  "CATEGORY_AMBIGUOUS": {
    "status": 409,
    "retryable": false
  },
  "FILE_CONFLICT": {
    "status": 409,
    "retryable": false
  },
  "TRANSFER_ID_IN_USE": {
    "status": 409,
    "retryable": false
  },
  "TRANSFER_CANCELLED": {
    "status": 409,
    "retryable": false
  },
  "PREVIEW_STALE": {
    "status": 409,
    "retryable": false
  },
  "OPERATION_IN_PROGRESS": {
    "status": 409,
    "retryable": true
  },
  "SOURCE_CHANGED": {
    "status": 409,
    "retryable": true
  },
  "IMPORT_NOT_READY": {
    "status": 409,
    "retryable": false
  },
  "PREWARM_BUSY": {
    "status": 409,
    "retryable": true
  },
  "PREWARM_REQUEST_CONFLICT": {
    "status": 409,
    "retryable": false
  },
  "ARTIFACT_TOO_LARGE": {
    "status": 413,
    "retryable": false
  },
  "PAYLOAD_TOO_LARGE": {
    "status": 413,
    "retryable": false
  },
  "UNSUPPORTED_MEDIA_TYPE": {
    "status": 415,
    "retryable": false
  },
  "LOGIN_RATE_LIMITED": {
    "status": 429,
    "retryable": true
  },
  "PREVIEW_LIMIT_EXCEEDED": {
    "status": 429,
    "retryable": true
  },
  "INTERNAL_ERROR": {
    "status": 500,
    "retryable": false
  },
  "UPSTREAM_UNAVAILABLE": {
    "status": 502,
    "retryable": true
  },
  "METADATA_UNTRUSTED": {
    "status": 502,
    "retryable": false
  },
  "CHANNELS_UNVERIFIED": {
    "status": 502,
    "retryable": true
  },
  "IMPORT_SOURCE_FAILED": {
    "status": 502,
    "retryable": true
  },
  "STORAGE_UNAVAILABLE": {
    "status": 503,
    "retryable": true
  },
  "NOT_READY": {
    "status": 503,
    "retryable": true
  },
  "SESSION_LIMIT_EXCEEDED": {
    "status": 503,
    "retryable": true
  },
  "TRANSFER_CAPACITY": {
    "status": 503,
    "retryable": true
  },
  "CACHE_CONTENDED": {
    "status": 503,
    "retryable": true
  },
  "PREVIEW_BUSY": {
    "status": 503,
    "retryable": true
  },
  "INSTALLER_UNAVAILABLE": {
    "status": 503,
    "retryable": false
  },
  "CACHE_MISS": {
    "status": 504,
    "retryable": false
  }
} as const;

export type CatalogErrorCode = keyof typeof errorCatalog;
