import { flushPromises, mount } from '@vue/test-utils';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import CacheRefresh from './CacheRefresh.vue';
import { resetStores, response } from '../testSupport';
import { signedIn } from '../session';
import type { MaintenancePreview } from '../maintenanceJobs';

beforeEach(() => { resetStores(); signedIn.value = true; });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); signedIn.value = false; });
it('pages through the server preview, refreshes the entire frozen selection and polls results without accumulating pages', async () => {
  vi.useFakeTimers();
  let state: MaintenancePreview['state'] = 'ready', completed = 0;
  const job = (): MaintenancePreview => ({ id: 'refresh-frozen', kind: 'refresh', state, match: { type: 'glob', pattern: '/releases/' }, created_at: '2026-10-03T00:00:00Z', expires_at: '2099-10-03T00:00:00Z', scanned_files: 30, selected_files: 30, selected_bytes: 30720, active_files: 0, completed_files: completed, failed_files: 0, ...(state === 'done' ? { result: { selected_files: 30, completed_files: 30, refreshed: 28, not_modified: 1, stale_fallback: 1, failed: 0, skipped: 0 } } : {}) });
  const fetch = vi.fn(async (url: string, init?: RequestInit) => {
    const request = new URL(url, 'https://admin.example');
    if (request.pathname.endsWith('/preview')) return response({ job: job() });
    if (request.pathname.endsWith('/items')) return response({ items: [{ ordinal: request.searchParams.has('cursor') ? 25 : 0, generation_id: 'gen', path: request.searchParams.has('cursor') ? '/last-page.zip' : '/first-page.zip', size_bytes: 1024, result_status: state === 'done' ? 'refreshed' : 'pending' }], next_cursor: request.searchParams.has('cursor') ? '' : 'page/+==', total_files: 30, total_bytes: 30720, state });
    if (request.pathname.endsWith('/execute')) { state = 'running'; return response({ job: job() }); }
    return response({ job: job() });
  });
  vi.stubGlobal('fetch', fetch);
  const wrapper = mount(CacheRefresh, { props: { application: 'acme/files' } });
  await wrapper.get('[name="match_pattern"]').setValue('/releases/');
  await wrapper.get('form').trigger('submit'); await flushPromises();
  expect(wrapper.get('.refresh-review').text()).toContain('30 files');
  expect(wrapper.get('.preview-files').text()).toContain('/first-page.zip');
  const navigation = wrapper.get('[aria-label="Preview file pages"]');
  await navigation.findAll('button').find((button) => button.attributes("aria-label") === 'Next page')!.trigger('click'); await flushPromises();
  expect(wrapper.get('.preview-files').text()).toContain('/last-page.zip');
  expect(wrapper.get('.preview-files').text()).not.toContain('/first-page.zip');
  expect(navigation.findAll('button').find((button) => button.attributes("aria-label") === 'Next page')!.attributes('disabled')).toBeDefined();
  const pageCalls = fetch.mock.calls.filter(([url]) => new URL(url, 'https://admin.example').pathname.endsWith('/items'));
  expect(pageCalls).toHaveLength(2);
  expect(new URL(pageCalls[1]![0], 'https://admin.example').searchParams.get('limit')).toBe('25');
  expect(new URL(pageCalls[1]![0], 'https://admin.example').searchParams.get('cursor')).toBe('page/+==');
  await wrapper.get('.refresh-review .danger').trigger('click'); await flushPromises();
  const execution = fetch.mock.calls.find(([url]) => url.endsWith('/execute'))!;
  expect(execution[0]).toBe('/admin/api/apps/acme/files/cache/refresh/refresh-frozen/execute');
  expect(JSON.parse(execution[1]!.body as string)).toEqual({});
  expect(wrapper.get('.refresh-job-state').text()).toContain('Running');
  expect(wrapper.text()).toContain('Leaving this page does not cancel the job');
  state = 'done'; completed = 30;
  await vi.advanceTimersByTimeAsync(5000); await flushPromises();
  expect(wrapper.get('.refresh-job-state').text()).toContain('30 completed');
  expect(wrapper.get('.refresh-summary').text()).toContain('28 refreshed · 1 not modified · 1 stale fallbacks');
  expect(wrapper.get('.preview-files').text()).toContain('/last-page.zip');
  expect(wrapper.get('.preview-files').text()).toContain('Refreshed');
  expect(wrapper.get('.preview-files').text()).not.toContain('/first-page.zip');
  expect(wrapper.emitted('changed')).toHaveLength(1);
  wrapper.unmount();
});

it('refreshes a single file without a preview and discards its late result after the application changes', async () => {
  let delayed = false, resolveOld: ((value: unknown) => void) | undefined;
  const fetch = vi.fn((url: string, init?: RequestInit) => delayed ? new Promise((resolve) => { resolveOld = resolve; }) : Promise.resolve(response({ item: { path: '/one.zip', status: 'refreshed', generation_id: 'new' } })));
  vi.stubGlobal('fetch', fetch);
  const wrapper = mount(CacheRefresh, { props: { application: 'acme/files' } });
  await wrapper.vm.refreshFile('one.zip'); await flushPromises();
  expect(fetch.mock.calls[0]![0]).toBe('/admin/api/apps/acme/files/cache/refresh');
  expect(JSON.parse(fetch.mock.calls[0]![1]!.body as string)).toEqual({ path: '/one.zip' });
  expect(wrapper.get('.single-refresh-result').text()).toContain('Refreshed');
  expect(fetch.mock.calls.some(([url]) => url.includes('/preview'))).toBe(false);
  delayed = true;
  const pending = wrapper.vm.refreshFile('/other.zip');
  const oldRequest = fetch.mock.calls.at(-1)![1]!;
  await wrapper.setProps({ application: 'acme/other' });
  expect(oldRequest.signal?.aborted).toBe(true);
  resolveOld?.(response({ item: { path: '/wrong-old-app.zip', status: 'stale_fallback' } }));
  await pending; await flushPromises();
  expect(wrapper.find('.single-refresh-result').exists()).toBe(false);
  expect(wrapper.emitted('changed')).toHaveLength(1);
  wrapper.unmount();
});
