<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,ref} from "vue";
import {useRouter} from "vue-router";
import {api,configurationDownload,isCancellation} from "../api";
import {t,errorText} from "../i18n";
import type {Configuration} from "../configuration";
import FilePicker from "./FilePicker.vue";
import IconButton from "./IconButton.vue";
import SelectMenu from "./SelectMenu.vue";
const props=defineProps<{action:"export"|"import"|"copy";kind?:"Vendor"|"App";recordKey?:string;sourceUID?:string}>();
const emit=defineEmits<{close:[];applied:[]}>();const router=useRouter();
const dialog=ref<HTMLDialogElement>(),busy=ref(false),loading=ref(true),error=ref<unknown>(),mode=ref("linked"),includeApps=ref(true),includeNotes=ref(false),includeCredentials=ref(false),source=ref<Configuration>(),targetVendor=ref(props.recordKey?.split('/')[0]||""),targetID=ref(""),vendors=ref<{id:string;name:{en:string;"zh-CN":string}}[]>([]),scope=ref<string[]>([]);
const file=ref<File>(),preview=ref<Preview>(),choices=ref<Record<string,Choice>>({}),changed=ref(false),trust=ref(false),confirmed=ref(false);
type Choice={kind:string;key:string;action?:string;target_vendor?:string;target_id?:string;dictionary_update?:boolean;proxy?:{mode:string;url?:string};keep_effective_proxy?:boolean;detach_template?:boolean;update_notes?:boolean;proxyResolution?:string;proxyURL?:string};
type Item={kind:string;key:string;target:string;action:string;revision:number;notes_revision:number;template_hash_mismatch:boolean;template_missing:boolean;detach_template:boolean;omitted_fields:string[];differences:{field:string;before:unknown;after:unknown}[];requirements:string[]};
type Preview={id:string;expires_at:string;preview:{items:Item[];ready:boolean;needs_instructions_trust:boolean}};
const title=computed(()=>t(props.action==="export"?"Export configuration":props.action==="copy"?"Copy application":"Import configuration"));
const modeOptions=computed(()=>[{value:"linked",label:t("Template and overrides")},{value:"independent",label:t("Independent copy")}].filter(x=>props.action!=="copy"||source.value?.template_ref||x.value==="independent"));
const vendorOptions=computed(()=>[{value:"",label:t("Use file identity")},...vendors.value.map(v=>({value:v.id,label:v.id}))]);
const appCount=computed(()=>preview.value?.preview.items.filter(x=>x.kind==="App").length||0);
const previous=document.activeElement as HTMLElement|null;let controller=new AbortController(),disposed=false;
function close(){if(!busy.value)emit("close")}
async function load(){loading.value=true;vendors.value=[];scope.value=[];error.value=undefined;try{
 if(props.action==="copy"){source.value=await api<Configuration>(`apps/${props.recordKey}/configuration`,undefined,controller.signal);mode.value=source.value.template_ref?"linked":"independent";}
 if(props.action!=="export"){for(let page=1;;page++){const result=await api<{items:typeof vendors.value;total_pages:number}>(`vendors?page=${page}&limit=100&state=current`,undefined,controller.signal);vendors.value.push(...result.items);if(page>=result.total_pages)break}}
 if(props.action==="export"&&props.kind==="Vendor"){scope.value=[props.recordKey!];for(let page=1;;page++){const result=await api<{items:{key:string}[];total_pages:number}>(`vendors/${props.recordKey}/apps?page=${page}&limit=100&state=current`,undefined,controller.signal);scope.value.push(...result.items.map(x=>x.key));if(page>=result.total_pages)break}}else if(props.action==="export")scope.value=[props.recordKey!.split('/')[0]!,props.recordKey!];
 }catch(reason){if(!disposed&&!isCancellation(reason))error.value=reason}finally{loading.value=false}}
onMounted(()=>{dialog.value?.showModal();void load()});onBeforeUnmount(()=>{disposed=true;controller.abort();file.value=undefined;choices.value={};preview.value=undefined;dialog.value?.close();previous?.focus()});
function chooseFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0];preview.value=undefined;choices.value={};trust.value=false;confirmed.value=false;error.value=undefined;changed.value=false;}
function mark(){changed.value=true;trust.value=false;confirmed.value=false;}
function itemChoice(item:Item){const key=`${item.kind}:${item.key}`;return choices.value[key] ||= {kind:item.kind,key:item.key,action:item.action};}
function serializedChoices(){return Object.values(choices.value).map(({proxyResolution,proxyURL,...choice})=>{if(proxyResolution==="keep_effective")choice.keep_effective_proxy=true;else if(proxyResolution&&proxyResolution!=="keep_current")choice.proxy={mode:proxyResolution,...(proxyResolution==="url"?{url:proxyURL||""}:{})};return choice})}
async function previewFile(){if(!file.value||busy.value)return;busy.value=true;error.value=undefined;try{const data=new FormData();data.append("file",file.value);data.append("choices",JSON.stringify(serializedChoices()));const result=await api<Preview>("configuration/import/preview",data,controller.signal);if(disposed)return;preview.value=result;changed.value=false;trust.value=false;confirmed.value=false;for(const item of result.preview.items)itemChoice(item);}catch(reason){if(!isCancellation(reason))error.value=reason}finally{busy.value=false}}
async function execute(){if(!preview.value||changed.value||!confirmed.value||busy.value)return;busy.value=true;error.value=undefined;try{await api(`configuration/import/${preview.value.id}/execute`,{confirm:true,trust_instructions:trust.value},controller.signal);emit("applied");emit("close")}catch(reason){if(!isCancellation(reason))error.value=reason}finally{busy.value=false}}
async function download(){busy.value=true;error.value=undefined;try{const blob=await configurationDownload({selection:[{kind:props.kind,key:props.recordKey,...(props.kind==="Vendor"?{include_apps:includeApps.value}:{})}],mode:mode.value,include_notes:includeNotes.value,include_proxy_credentials:includeCredentials.value},controller.signal);if(disposed)return;const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="redapp-configuration.zip";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(reason){if(!isCancellation(reason))error.value=reason}finally{busy.value=false}}
async function copy(){if(!source.value||busy.value)return;busy.value=true;error.value=undefined;try{let notes_revision=0;if(includeNotes.value){notes_revision=(await api<{revision:number}>(`apps/${props.recordKey}/admin-notes`,undefined,controller.signal)).revision};const result=await api<{app:{key:string}}>(`apps/${props.recordKey}/copy`,{source_uid:props.sourceUID,source_revision:source.value.revision,target_vendor:targetVendor.value,target_id:targetID.value,mode:mode.value,include_notes:includeNotes.value,notes_revision},controller.signal);emit("close");await router.push(`/admin/vendors/${result.app.key.split("/")[0]}/apps/${result.app.key.split("/")[1]}/settings`);}catch(reason){if(!isCancellation(reason))error.value=reason}finally{busy.value=false}}
function requirementText(value:string){const requirements:Record<string,string>={confirm_detach_template:t("Confirm template detachment before applying."),resolve_omitted_proxy:t("Choose a proxy setting for this new entity."),resolve_changed_proxy:t("Resolve the proxy change caused by template rebinding."),confirm_notes_update:t("Confirm the Admin Notes update before applying.")};return requirements[value]||t("Resolve import choices before applying.")}
function text(value:unknown){return typeof value==="string"?value:JSON.stringify(value,null,2)}
</script>
<template>
 <dialog ref="dialog" class="history-dialog configuration-exchange" :aria-label="title" @cancel.prevent="close"><div class="dialog-heading"><h2>{{title}}</h2><IconButton icon="close" :label="t('Close')" :disabled="busy" @click="close" /></div>
 <p v-if="error" class="error" role="alert">{{errorText(error)}}<IconButton icon="refresh" :label="t('Retry')" :disabled="busy" @click="load" /></p>
 <template v-if="action==='export'"><p>{{t('Package scope')}}</p><ul><li v-for="key in (kind==='Vendor'&&!includeApps?scope.slice(0,1):scope)" :key="key">{{key}}</li><li>{{t('Referenced dictionary entries and controlled static images')}}</li></ul><form @submit.prevent="download"><fieldset :disabled="busy||loading"><label v-if="kind==='Vendor'"><input v-model="includeApps" type="checkbox" />{{t('Include applications')}}</label><SelectMenu v-model="mode" :options="modeOptions" :label="t('Template mode')" /><label><input v-model="includeNotes" type="checkbox" />{{t('Include Admin Notes (sensitive)')}}</label><label><input v-model="includeCredentials" type="checkbox" />{{t('Include proxy credentials (sensitive)')}}</label><p class="notice">{{t('Sensitive options are off by default. Store this package securely.')}}</p><button>{{t('Download ZIP')}}</button></fieldset></form></template>
 <form v-else-if="action==='copy'" @submit.prevent="copy"><fieldset :disabled="busy||loading||!source"><SelectMenu v-model="targetVendor" :options="vendorOptions.filter(x=>x.value)" :label="t('Target vendor')" /><label>{{t('New application ID')}}<input v-model="targetID" required maxlength="63" pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label><SelectMenu v-model="mode" :options="modeOptions" :label="t('Template mode')" /><p class="notice">{{t('The new application is disabled and has no old cache, statistics, tasks or hosted files. Inherited proxy settings resolve under the target vendor.')}}</p><label><input v-model="includeNotes" type="checkbox" />{{t('Include Admin Notes (sensitive)')}}</label><button>{{t('Copy application')}}</button></fieldset></form>
 <template v-else><FilePicker name="file" :label="t('Choose configuration ZIP or YAML')" accept=".zip,.yaml,.yml" :file-name="file?.name" :disabled="busy" @change="chooseFile" /><p class="muted">{{t('Missing templates require an independent copy. New entities start disabled.')}}</p><button :disabled="!file||busy" @click="previewFile">{{t('Generate preview')}}</button>
 <template v-if="preview"><p>{{t('Preview expires after ten minutes. Changed choices require a new preview.')}}</p><section v-for="item in preview.preview.items" :key="`${item.kind}:${item.key}`" class="panel"><h3>{{item.kind}} · {{item.key}} → {{item.target}}</h3><p>{{t('Current revision')}}: {{item.revision}} · {{t('Notes revision')}}: {{item.notes_revision}}</p>
 <label v-if="item.kind==='categories'||item.kind==='tags'"><input v-model="itemChoice(item).dictionary_update" type="checkbox" :disabled="busy" @change="mark" />{{t('Update existing dictionary names')}}</label>
 <template v-else><SelectMenu :model-value="itemChoice(item).action||item.action" :options="[{value:'skip',label:t('Skip')},{value:item.revision?'update':'create',label:t(item.revision?'Update':'Create')}]" :label="t('Import action')" :disabled="busy" @update:model-value="itemChoice(item).action=$event;mark()" />
 <template v-if="item.kind==='App'&&appCount===1"><SelectMenu :model-value="itemChoice(item).target_vendor||''" :options="vendorOptions" :label="t('Target vendor')" :disabled="busy" @update:model-value="itemChoice(item).target_vendor=$event;itemChoice(item).action=undefined;mark()" /><label>{{t('New application ID')}}<input v-model="itemChoice(item).target_id" :disabled="busy" :placeholder="item.key.split('/')[1]" @input="itemChoice(item).action=undefined;mark()" /></label></template>
 <p v-if="item.template_hash_mismatch" class="notice">{{t('Template differs from the exported hash; the target template will be used.')}}</p><p v-if="item.template_missing" class="notice">{{t('Template unavailable; the last accepted defaults remain in use.')}}</p>
 <label v-if="item.detach_template"><input v-model="itemChoice(item).detach_template" type="checkbox" :disabled="busy" @change="mark" />{{t('Detach the existing template relationship')}}</label>
 <template v-if="item.omitted_fields.includes('proxy')"><p class="notice">{{t('Proxy was omitted. Resolve it explicitly for new entities or changed inheritance.')}}</p><SelectMenu :model-value="itemChoice(item).proxyResolution||(item.revision?'keep_current':'')" :options="[{value:'keep_current',label:t('Keep current own setting')},{value:'keep_effective',label:t('Keep current effective proxy')},{value:'inherit',label:t('Inherit')},{value:'direct',label:t('Direct')},{value:'url',label:t('Proxy URL')}]" :label="t('Proxy resolution')" :disabled="busy" @update:model-value="itemChoice(item).proxyResolution=$event;mark()" /><label v-if="itemChoice(item).proxyResolution==='url'">{{t('Proxy URL')}}<input v-model="itemChoice(item).proxyURL" :disabled="busy" autocomplete="off" @input="mark" /></label></template>
 <label v-if="item.differences.some(x=>x.field==='admin_notes')"><input v-model="itemChoice(item).update_notes" type="checkbox" :disabled="busy" @change="mark" />{{t('Update Admin Notes explicitly')}}</label></template>
 <p v-for="required in item.requirements" :key="required" class="notice">{{requirementText(required)}}</p><details v-for="diff in item.differences" :key="diff.field"><summary>{{diff.field}}</summary><div class="configuration-diff"><div><strong>{{t('Current')}}</strong><pre>{{text(diff.before)}}</pre></div><div><strong>{{t('Proposed')}}</strong><pre>{{text(diff.after)}}</pre></div></div></details></section>
 <p class="notice">{{t('Instructions are shown as source text. Saving changed instructions trusts their HTML and JavaScript.')}}</p><label v-if="preview.preview.needs_instructions_trust"><input v-model="trust" type="checkbox" :disabled="busy||changed" />{{t('I trust the imported instruction source')}}</label><label><input v-model="confirmed" type="checkbox" :disabled="busy||changed" />{{t('Apply the complete reviewed package')}}</label><button :disabled="busy||changed||!preview.preview.ready||!confirmed||(preview.preview.needs_instructions_trust&&!trust)" @click="execute">{{t('Execute import')}}</button>
 </template></template>
 </dialog>
</template>
