import {mount,flushPromises} from "@vue/test-utils";
import {beforeEach,afterEach,expect,it,vi} from "vitest";
import {createMemoryHistory,createRouter} from "vue-router";
import ConfigurationExchange from "./ConfigurationExchange.vue";
import {resetStores,response,configurationFixture,selectValue} from "../testSupport";
import {signedIn} from "../session";
import {setLanguage} from "../i18n";
beforeEach(()=>{resetStores();signedIn.value=true;vi.spyOn(HTMLDialogElement.prototype,'showModal').mockImplementation(()=>{});vi.spyOn(HTMLDialogElement.prototype,'close').mockImplementation(()=>{})});afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();setLanguage('en');document.body.innerHTML=''});
async function component(action:'import'|'copy'|'export'){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:{template:'<div />'}}]});await router.push('/admin/vendors');await router.isReady();return {router,wrapper:mount(ConfigurationExchange,{props:{action,kind:'App',recordKey:'openai/codex',sourceUID:'source-uid'},global:{plugins:[router]},attachTo:document.body})}}
it('exports scoped ZIP with sensitive defaults off on every reopen',async()=>{
 vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn(()=> 'blob:fixture'),revokeObjectURL:vi.fn()}));vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
 const fetch=vi.fn(async(_url:string,init?:RequestInit)=>({...response({}),blob:async()=>new Blob(['ZIP']),headers:new Headers({'Content-Type':'application/zip'})}));vi.stubGlobal('fetch',fetch);
 let {wrapper}=await component('export');await flushPromises();expect(wrapper.text()).toContain('openai');expect(wrapper.text()).toContain('openai/codex');const fields=wrapper.findAll('input[type="checkbox"]');expect(fields.map(x=>(x.element as HTMLInputElement).checked)).toEqual([false,false]);await wrapper.get('form').trigger('submit');await flushPromises();expect(JSON.parse(fetch.mock.calls[0]![1]!.body as string)).toMatchObject({selection:[{kind:'App',key:'openai/codex'}],include_notes:false,include_proxy_credentials:false,mode:'linked'});
 await fields[0]!.setValue(true);await fields[1]!.setValue(true);wrapper.unmount();({wrapper}=await component('export'));await flushPromises();expect(wrapper.findAll('input[type="checkbox"]').every(x=>!(x.element as HTMLInputElement).checked)).toBe(true);wrapper.unmount();
});
it('shows instruction diffs as inert source and requires regenerated choices and trusted execution',async()=>{
 const malicious='<script>fetch("https://must-not-fetch.invalid")</script><iframe src="https://must-not-fetch.invalid"></iframe>';
 let n=0;const fetch=vi.fn(async(url:string,init?:RequestInit)=>{if(url.includes('/preview'))return response({id:`preview-${++n}`,expires_at:'future',preview:{ready:true,needs_instructions_trust:true,items:[{kind:'App',key:'openai/codex',target:'openai/codex',action:'skip',revision:2,notes_revision:0,template_hash_mismatch:true,template_missing:false,detach_template:false,omitted_fields:[],requirements:[],differences:[{field:'instructions.en',before:'Old',after:malicious}]}]}});if(url.includes('/execute'))return response({applied:true});return response({items:[],total_pages:1})});vi.stubGlobal('fetch',fetch);
 const {wrapper}=await component('import');await flushPromises();const input=wrapper.get('input[type=file]');Object.defineProperty(input.element,'files',{value:[new File(['kind: App'],'source.yaml')],configurable:true});await input.trigger('change');await wrapper.findAll('button').find(x=>x.text()==='Generate preview')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain(malicious);expect(wrapper.find('script').exists()).toBe(false);expect(wrapper.find('iframe').exists()).toBe(false);expect(fetch.mock.calls.some(([url])=>url.includes('must-not-fetch'))).toBe(false);
 await selectValue(wrapper.get('.panel .select-menu'),'update');expect(wrapper.findAll('button').find(x=>x.text()==='Execute import')!.attributes('disabled')).toBeDefined();await wrapper.findAll('button').find(x=>x.text()==='Generate preview')!.trigger('click');await flushPromises();const checkboxes=wrapper.findAll('input[type=checkbox]');await checkboxes[0]!.setValue(true);await checkboxes[1]!.setValue(true);await wrapper.findAll('button').find(x=>x.text()==='Execute import')!.trigger('click');await flushPromises();const call=fetch.mock.calls.find(([url])=>url.includes('/execute'))!;expect(call[0]).toContain('/preview-2/execute');expect(JSON.parse(call[1]!.body as string)).toEqual({confirm:true,trust_instructions:true});expect(wrapper.emitted('applied')).toHaveLength(1);wrapper.unmount();
});
it('copies with source CAS, notes off, and navigates to the new application',async()=>{
 const fetch=vi.fn(async(url:string,init?:RequestInit)=>response(url.endsWith('/configuration')?configurationFixture({proxy:{mode:'inherit'}},7,'openai/codex'):url.endsWith('/copy')?{app:{key:'target/clone'}}:{items:[{id:'target',name:{en:'Target','zh-CN':'目标'}}],total_pages:1}));vi.stubGlobal('fetch',fetch);const {wrapper,router}=await component('copy');await flushPromises();await selectValue(wrapper.get('.select-menu'),'target');await wrapper.get('input[maxlength="63"]').setValue('clone');await wrapper.get('form').trigger('submit');await flushPromises();const call=fetch.mock.calls.find(([url])=>url.endsWith('/copy'))!;expect(JSON.parse(call[1]!.body as string)).toMatchObject({source_uid:'source-uid',source_revision:7,target_vendor:'target',target_id:'clone',mode:'linked',include_notes:false});expect(router.currentRoute.value.path).toBe('/admin/vendors/target/apps/clone/settings');setLanguage('zh-CN');await flushPromises();expect(wrapper.text()).toContain('复制应用');wrapper.unmount();
});
