<script setup lang="ts">
import {ref} from 'vue'
import {api,bytes,type CleanupPreview} from '../api'
const emit=defineEmits<{error:[unknown];expired:[];changed:[]}>()
const ttl=ref(60),oldPassword=ref(''),newPassword=ref(''),minimum=ref(''),preview=ref<CleanupPreview>(),busy=ref(false),message=ref('')
async function run(action:()=>Promise<void>){busy.value=true;message.value='';try{await action()}catch(error){emit('error',error)}finally{busy.value=false}}
async function save(){await run(async()=>{await api('settings',{latest_ttl_seconds:ttl.value});message.value='latest TTL saved'})}
async function password(){await run(async()=>{await api('password',{old:oldPassword.value,new:newPassword.value});oldPassword.value='';newPassword.value='';emit('expired')})}
async function plan(){preview.value=undefined;await run(async()=>{preview.value=await api<CleanupPreview>('cleanup/preview',{minimum_version:minimum.value});message.value='Review the selected generations before confirming'})}
async function clean(){const selected=preview.value;if(!selected)return;await run(async()=>{await api('cleanup/execute',{cleanup_id:selected.job.ID});preview.value=undefined;message.value='Cleanup executed; space is reclaimed after existing readers and writers finish';emit('changed')})}
</script>
<template><section><h2>Security and maintenance</h2><p role="status">{{message}}</p><div class="two-columns"><form @submit.prevent="save"><h3>Metadata freshness</h3><label>latest TTL (seconds)<input v-model.number="ttl" type="number" min="1" max="86400" required></label><button :disabled="busy">Save TTL</button></form><form @submit.prevent="password"><h3>Change password</h3><label>Current password<input v-model="oldPassword" type="password" autocomplete="current-password" required></label><label>New password (at least 12 bytes)<input v-model="newPassword" type="password" minlength="12" autocomplete="new-password" required></label><button :disabled="busy">Change password and sign out</button></form></div><form class="cleanup" @submit.prevent="plan"><h3>Version cleanup</h3><label>Minimum version to keep<input v-model="minimum" placeholder="0.150.0" required @input="preview=undefined"></label><button :disabled="busy">Preview cleanup</button></form><div v-if="preview" class="cleanup-review"><h3>Confirm this preview</h3><p>{{preview.job.Selected?.length||0}} generations · {{bytes(preview.logical_bytes)}} logical bytes · {{preview.active}} active</p><p v-if="preview.unknown_versions?.length">Unknown versions retained: {{preview.unknown_versions.join(', ')}}</p><details><summary>Selected generations</summary><pre>{{JSON.stringify(preview.job.Selected,null,2)}}</pre></details><p>Only previewed generations are retired. Later generations remain available. Existing readers and writers drain before disk space is reclaimed.</p><button class="danger" :disabled="busy" @click="clean">Confirm cleanup</button> <button class="secondary" :disabled="busy" @click="preview=undefined">Cancel</button></div></section></template>
