<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {api,type ProxySettings} from '../api'
const emit=defineEmits<{error:[unknown]}>();const server=ref(''),username=ref(''),password=ref(''),action=ref('keep'),saved=ref<ProxySettings>(),busy=ref(false),message=ref('')
async function load(){busy.value=true;try{saved.value=await api<ProxySettings>('proxy');server.value=saved.value.server}catch(error){emit('error',error)}finally{busy.value=false}}
async function save(){busy.value=true;message.value='';try{saved.value=await api<ProxySettings>('proxy',{server:server.value,username:action.value==='replace'?username.value:'',password:action.value==='replace'?password.value:'',password_action:action.value});username.value='';password.value='';action.value='keep';message.value='Proxy saved; new upstream requests use this configuration. Active transfers continue.'}catch(error){emit('error',error)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section><h2>Upstream proxy</h2><p class="muted">Optional HTTP / HTTPS / SOCKS5 proxy for metadata, artifacts and resume requests. Empty means direct; environment proxy variables are ignored. SOCKS5 uses proxy-side DNS; the proxy must be trusted.</p><p role="status">{{message}}</p><p v-if="busy&&!saved" role="status">Loading proxy settings…</p><form @submit.prevent="save"><label>Proxy server<input v-model="server" placeholder="http://proxy.example:3128" autocomplete="off"></label><p class="muted">{{saved?.has_credentials?'Credentials saved (never displayed)':'No saved credentials'}}</p><label>Saved credentials<select v-model="action"><option value="keep">Keep saved credentials</option><option value="replace">Replace credentials</option><option value="clear">Clear credentials</option></select></label><template v-if="action==='replace'"><label>Username<input v-model="username" autocomplete="off"></label><label>Password<input v-model="password" type="password" autocomplete="new-password"></label></template><p class="muted">Changing the server requires clearing or replacing saved credentials. Credentials are stored in the local SQLite database under data-directory permissions; no extra storage encryption is applied.</p><button :disabled="busy">{{busy?'Saving…':'Save proxy'}}</button> <button class="secondary" type="button" :disabled="busy" @click="load">Reload</button></form></section></template>
