import { flushPromises, mount } from '@vue/test-utils';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { createMemoryHistory, createRouter } from 'vue-router';
import AppShell from './AppShell.vue';
import { resetStores, response } from '../testSupport';
import { setLanguage } from '../i18n';
const ranking = Array.from({length: 8}, (_,i) => ({ id: `vendor/app-${i}`, name: { en: `Popular ${i}`, 'zh-CN': `热门 ${i}` }, icon: '', detail_url: `/vendor/app-${i}`, download_clients: 444444 }));
beforeEach(() => { resetStores(); setLanguage('en'); vi.useFakeTimers(); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); setLanguage('en'); document.body.innerHTML=''; });
async function setup(admin = false) {
  const router=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:{template:'<main />'}}]});
  await router.push('/'); await router.isReady();
  const wrapper=mount(AppShell,{props:{admin},global:{plugins:[router]},attachTo:document.body});
  return {wrapper,router,input:wrapper.get('.public-search input'),search:wrapper.get('.public-search')};
}
async function tick() { await vi.advanceTimersByTimeAsync(210); await flushPromises(); }
it.each([false,true])('uses public popular candidates and preserves bilingual mouse/keyboard navigation (admin=%s)',async(admin)=>{
  const fetch=vi.fn(async(url:string)=>{expect(url).toBe('/api/home');return response({ranking,pinned:[{name:{en:'Not a popular candidate'}}]});});
  vi.stubGlobal('fetch',fetch);
  const {wrapper,router,input,search}=await setup(admin);
  expect(search.find('[role=listbox]').exists()).toBe(false);
  await input.trigger('focus');
  expect(search.get('[role=status]').text()).toBe('Loading…');
  await tick();
  expect(search.findAll('[role=option]')).toHaveLength(6);
  expect(search.get('[role=listbox]').attributes('aria-label')).toBe('Popular applications');
  expect(search.text()).not.toContain('444444');expect(search.text()).not.toContain('Not a popular candidate');
  setLanguage('zh-CN');await flushPromises();
  expect(search.get('[role=listbox]').attributes('aria-label')).toBe('热门应用');expect(search.text()).toContain('热门 0');
  await input.trigger('keydown',{key:'ArrowUp'});
  expect(search.get('[aria-selected=true]').text()).toContain('热门 5');
  await input.trigger('keydown',{key:'Enter'});await flushPromises();
  expect(router.currentRoute.value.path).toBe('/vendor/app-5');expect(search.find('[role=listbox]').exists()).toBe(false);
  await input.trigger('focus');await tick();
  await input.trigger('keydown',{key:'Escape'});expect(search.find('[role=listbox]').exists()).toBe(false);
  await input.trigger('keydown',{key:'ArrowDown'});await tick();
  await search.findAll('[role=option]')[1]!.trigger('click');await flushPromises();
  expect(router.currentRoute.value.path).toBe('/vendor/app-1');
  await input.trigger('focus');await tick();
  document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));await flushPromises();
  expect(search.find('[role=listbox]').exists()).toBe(false);
  wrapper.unmount();
});
it('isolates popular/search responses across rapid typing, whitespace clearing and blur',async()=>{
  const pending:{url:string;signal:AbortSignal;resolve:(value:ReturnType<typeof response>)=>void}[]=[];
  vi.stubGlobal('fetch',vi.fn((url:string,init:RequestInit)=>new Promise<ReturnType<typeof response>>(resolve=>pending.push({url,signal:init.signal as AbortSignal,resolve}))));
  const {wrapper,input,search}=await setup();
  await input.trigger('focus');await tick();
  await input.setValue('needle');await tick();
  expect(pending[0]!.signal.aborted).toBe(true);expect(pending[1]!.url).toBe('/api/search?q=needle');
  pending[0]!.resolve(response({ranking}));await flushPromises();expect(search.find('[role=option]').exists()).toBe(false);
  await input.setValue('   ');await tick();expect(pending[2]!.url).toBe('/api/home');
  pending[1]!.resolve(response({items:[{kind:'app',id:'wrong',name:{en:'Stale result'},url:'/wrong',icon:''}]}));await flushPromises();
  expect(search.text()).not.toContain('Stale result');
  await search.trigger('focusout',{relatedTarget:document.body});expect(pending[2]!.signal.aborted).toBe(true);
  pending[2]!.resolve(response({ranking}));await flushPromises();expect(search.find('[role=listbox]').exists()).toBe(false);
  await input.trigger('focus');await tick();pending[3]!.resolve(response({ranking:[]}));await flushPromises();
  expect(search.text()).toContain('No popular applications yet.');
  setLanguage('zh-CN');await flushPromises();expect(search.text()).toContain('暂无热门应用');
  wrapper.unmount();
});
it('shows popular errors and retries on activation without changing normal text search',async()=>{
  let failed=true;
  vi.stubGlobal('fetch',vi.fn(async(url:string)=>url==='/api/home'?failed?response({error:{code:'INTERNAL_ERROR'}},503):response({ranking}):response({items:[{kind:'app',id:'found/app',name:{en:'Found', 'zh-CN':'找到'},url:'/found/app',icon:''}]})));
  const {wrapper,input,search,router}=await setup();
  await input.trigger('focus');await tick();expect(search.text()).toContain('Popular applications unavailable.');
  await input.trigger('keydown',{key:'Escape'});failed=false;
  await input.trigger('focus');await tick();expect(search.findAll('[role=option]')).toHaveLength(6);
  await input.setValue('Found');await tick();expect(search.findAll('[role=option]')).toHaveLength(1);expect(search.text()).not.toContain('Popular applications');
  await input.trigger('keydown',{key:'ArrowDown'});await input.trigger('keydown',{key:'Enter'});await flushPromises();
  expect(router.currentRoute.value.path).toBe('/found/app');
  wrapper.unmount();
});
