import { mount, flushPromises } from "@vue/test-utils";
import { afterEach, expect, it } from "vitest";
import VendorLogo from "./VendorLogo.vue";
import { setLanguage } from "../i18n";
afterEach(() => setLanguage("en"));
it("uses only the current language then default, with bounded failure fallback and no empty frame", async () => {
  setLanguage("en");
  const wrapper = mount(VendorLogo, { props: { vendor: { icon: "/default.svg", localized_icons: { en: "/english.svg", "zh-CN": "/chinese.svg" } } } });
  expect(wrapper.get("img").attributes("src")).toBe("/english.svg");
  expect(wrapper.get(".entity-icon").classes()).toContain("entity-icon--loading");
  await wrapper.get("img").trigger("load");
  expect(wrapper.get(".entity-icon").classes()).not.toContain("entity-icon--loading");
  await wrapper.get("img").trigger("error");
  expect(wrapper.get("img").attributes("src")).toBe("/default.svg");
  await wrapper.get("img").trigger("error");
  expect(wrapper.find(".entity-icon").exists()).toBe(false);
  setLanguage("zh-CN"); await flushPromises();
  expect(wrapper.get("img").attributes("src")).toBe("/chinese.svg");
  await wrapper.setProps({ vendor: { icon: "/default.svg", localized_icons: { en: "/english.svg", "zh-CN": "" } } });
  expect(wrapper.get("img").attributes("src")).toBe("/default.svg");
  await wrapper.setProps({ vendor: { icon: "", localized_icons: { en: "/english.svg", "zh-CN": "" } } });
  expect(wrapper.find(".entity-icon").exists()).toBe(false);
  setLanguage("en"); await flushPromises();
  expect(wrapper.get("img").attributes("src")).toBe("/english.svg");
  await wrapper.setProps({ admin: true });
  expect(wrapper.get("img").attributes("src")).toBe("/admin/api/assets/builtin-icon?path=%2Fenglish.svg");
  await wrapper.setProps({ vendor: { icon: "", localized_icons: { en: "", "zh-CN": "" } } });
  expect(wrapper.find(".entity-icon").exists()).toBe(false);
  wrapper.unmount();
});
