// Package cachepolicy owns typed HTTP cache and automatic-cleanup rules. It
// deliberately does not decide upstream Cache-Control precedence or stale policy.
package cachepolicy

import (
	"errors"
	"fmt"
	"regexp"

	"github.com/PMExtra/RedApp/internal/pathmatch"
)

const (
	MaxRules            = 32
	MaxTTLSeconds       = 86400
	MinAgeSeconds int64 = 60
	MaxAgeSeconds int64 = 315360000
)

var ErrInvalidPolicy = errors.New("invalid HTTP cache policy")

type CacheRule struct {
	ID         string         `json:"id,omitempty"`
	Match      pathmatch.Spec `json:"match"`
	TTLSeconds int            `json:"ttl_seconds"`
}

type CleanupRule struct {
	Match      pathmatch.Spec `json:"match"`
	Basis      string         `json:"basis"`
	AgeSeconds int64          `json:"age_seconds"`
}

type Config struct {
	StaleFallback bool          `json:"stale_fallback"`
	Rules         []CacheRule   `json:"rules"`
	AutoCleanup   []CleanupRule `json:"auto_cleanup"`
}

func Empty() Config {
	return Config{StaleFallback: true, Rules: []CacheRule{}, AutoCleanup: []CleanupRule{}}
}
func (c Config) Validate() error { _, err := Compile(c); return err }

// Normalize validates and copies input, preserving zero TTL as a cache rule.
// IDs for newly created rules are generated by the persistence boundary.
func Normalize(config Config) (Config, error) {
	p, err := Compile(config)
	if err != nil {
		return Config{}, err
	}
	out := Empty()
	out.StaleFallback = config.StaleFallback
	out.Rules = append(out.Rules, p.rules...)
	out.AutoCleanup = append(out.AutoCleanup, p.cleanup...)
	return out, nil
}

var ruleID = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,64}$`)

type Policy struct {
	staleFallback   bool
	rules           []CacheRule
	cleanup         []CleanupRule
	ruleMatchers    []*pathmatch.Matcher
	cleanupMatchers []*pathmatch.Matcher
}

func Compile(config Config) (*Policy, error) {
	if len(config.Rules) > MaxRules || len(config.AutoCleanup) > MaxRules {
		return nil, fmt.Errorf("%w: each rule list supports at most %d entries", ErrInvalidPolicy, MaxRules)
	}
	p := &Policy{staleFallback: config.StaleFallback, rules: append([]CacheRule(nil), config.Rules...), cleanup: append([]CleanupRule(nil), config.AutoCleanup...)}
	seen := map[string]bool{}
	for i, rule := range p.rules {
		if rule.ID != "" {
			if !ruleID.MatchString(rule.ID) || seen[rule.ID] {
				return nil, fmt.Errorf("%w: rules[%d].id must be unique and contain at most 64 ASCII letters, digits, underscores or hyphens", ErrInvalidPolicy, i)
			}
			seen[rule.ID] = true
		}
		if rule.TTLSeconds < 0 || rule.TTLSeconds > MaxTTLSeconds {
			return nil, fmt.Errorf("%w: rules[%d].ttl_seconds must be 0..%d", ErrInvalidPolicy, i, MaxTTLSeconds)
		}
		matcher, err := pathmatch.Compile(rule.Match)
		if err != nil {
			return nil, fmt.Errorf("%w: rules[%d].match: %w", ErrInvalidPolicy, i, err)
		}
		p.ruleMatchers = append(p.ruleMatchers, matcher)
	}
	for i, rule := range p.cleanup {
		if rule.Basis != "fetched_at" && rule.Basis != "last_access" {
			return nil, fmt.Errorf("%w: auto_cleanup[%d].basis must be fetched_at or last_access", ErrInvalidPolicy, i)
		}
		if rule.AgeSeconds < MinAgeSeconds || rule.AgeSeconds > MaxAgeSeconds {
			return nil, fmt.Errorf("%w: auto_cleanup[%d].age_seconds must be %d..%d", ErrInvalidPolicy, i, MinAgeSeconds, MaxAgeSeconds)
		}
		matcher, err := pathmatch.Compile(rule.Match)
		if err != nil {
			return nil, fmt.Errorf("%w: auto_cleanup[%d].match: %w", ErrInvalidPolicy, i, err)
		}
		p.cleanupMatchers = append(p.cleanupMatchers, matcher)
	}
	return p, nil
}

// StaleFallback reports the explicit policy captured with this compiled snapshot.
func (p *Policy) StaleFallback() bool { return p == nil || p.staleFallback }

// CacheRule selects the first path match. A missing match leaves the existing
// source/application TTL policy unchanged; the model invents no fallback mode.
func (p *Policy) CacheRule(path string) (CacheRule, int, bool) {
	if p != nil {
		for i, matcher := range p.ruleMatchers {
			if matcher.Match(path) {
				return p.rules[i], i, true
			}
		}
	}
	return CacheRule{}, -1, false
}

// CleanupRule selects by path before the caller evaluates age. An older file
// never falls through a first matching rule to a later, less restrictive rule.
func (p *Policy) CleanupRule(path string) (CleanupRule, int, bool) {
	if p != nil {
		for i, matcher := range p.cleanupMatchers {
			if matcher.Match(path) {
				return p.cleanup[i], i, true
			}
		}
	}
	return CleanupRule{}, -1, false
}
