'use strict';
const el=id=>document.getElementById(id);let csrf='',cleanup='',selectedVersion='';
const show=(id,yes)=>el(id).hidden=!yes;
const bytes=n=>`${(n/1048576).toFixed(2)} MiB`;
async function api(path,body){const r=await fetch('/admin/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok){if(r.status===401){show('login',true);show('dashboard',false)}throw Error(data.error||'Request failed')}return data}
function notice(s){el('notice').textContent=s}
async function run(f){try{await f()}catch(e){notice(e.message)}}
function cell(tr,s){const td=document.createElement('td');td.textContent=s;tr.append(td)}
async function refresh(){const d=await api('status');show('login',false);show('dashboard',true);el('cards').replaceChildren();for(const [label,n] of [['Cache',d.disk.cache_bytes],['Temporary',d.disk.temporary_bytes],['Pending deletion',d.disk.pending_bytes],['Service disk usage',d.disk.used_bytes],['Filesystem available',d.disk.free_bytes]]){const card=document.createElement('div');card.className='card';card.textContent=label+'\n'+bytes(n);el('cards').append(card)}for(const [label,key] of [['Recent upstream speed','upstream_bytes_per_second'],['Recent downstream speed','downstream_bytes_per_second']]){const card=document.createElement('div');card.className='card';card.textContent=label+'\n'+bytes(d.rates[key])+'/s';el('cards').append(card)}el('versions').replaceChildren();for(const [v,t] of Object.entries(d.versions)){const p=document.createElement('p');const count=d.counters['version:'+v+':requests']||0;p.textContent=v+' · First seen '+t+' · Artifact requests: '+count+' ';const button=document.createElement('button');button.textContent='View resources';button.onclick=()=>{selectedVersion=v;renderResources(d.resources)};p.append(button);el('versions').append(p)}renderResources(d.resources);el('counters').textContent=JSON.stringify(d.counters,null,2);el('events').textContent=JSON.stringify(d.events,null,2);el('system').textContent=`${d.os}/${d.arch} · ${d.go} · ${d.goroutines} goroutines · ${bytes(d.memory_bytes)} memory · snapshot ${d.sampled_at}`;el('install').textContent=`curl -fsS '${d.public_base_url}/install.sh' -o install.sh && sh install.sh\nPowerShell: Invoke-WebRequest '${d.public_base_url}/install.ps1' -OutFile install.ps1; ./install.ps1`;const clear=document.createElement('button');clear.textContent='Show all versions';clear.onclick=()=>{selectedVersion='';renderResources(d.resources)};el('versions').append(clear);const freed=document.createElement('div');freed.className='card';freed.textContent='Logical bytes reclaimed by cleanup\n'+bytes(d.counters.cleanup_freed_bytes||0);el('cards').append(freed);notice('Status updated')}
el('login-form').onsubmit=e=>{e.preventDefault();run(async()=>{const d=await api('login',{password:el('password').value});el('password').value='';csrf=d.csrf;await refresh()})};
el('refresh').onclick=()=>run(refresh);
el('logout').onclick=()=>run(async()=>{await api('logout',{});csrf='';show('dashboard',false);show('login',true)});
el('ttl-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('settings',{latest_ttl_seconds:Number(el('ttl').value)});notice('latest TTL saved')})};
el('change-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('password',{old:el('old').value,new:el('new').value});el('old').value='';el('new').value='';csrf='';show('dashboard',false);show('login',true);notice('Password updated; sign in again')})};
el('cleanup-form').onsubmit=e=>{e.preventDefault();run(async()=>{const d=await api('cleanup/preview',{minimum_version:el('minimum').value});cleanup=d.job.ID;el('preview').textContent=JSON.stringify(d,null,2);show('execute',true)})};
el('execute').onclick=()=>run(async()=>{await api('cleanup/execute',{cleanup_id:cleanup});show('execute',false);el('preview').textContent='Cleanup executed; files are reclaimed after existing leases end';await refresh()});
run(async()=>{const s=await api('session');csrf=s.csrf;await refresh()});

function renderResources(resources){el('resources').replaceChildren();for(const r of resources.filter(r=>!selectedVersion||r.Resource.Labels.version===selectedVersion)){const tr=document.createElement('tr');cell(tr,r.Resource.Labels.version+' / '+r.Resource.Labels.name);cell(tr,r.ID.slice(0,8)+' · '+r.State+(r.Retired?' (pending deletion)':''));cell(tr,bytes(r.Bytes)+' / '+r.Readers);cell(tr,bytes(r.AverageBPS)+'/s · '+bytes(r.RecentBPS)+'/s');cell(tr,r.Resumes+' / '+(r.VerificationNS/1e6).toFixed(1)+' ms');cell(tr,r.Started+' / '+r.Finished+' · '+(r.Error||'none'));el('resources').append(tr)}}
