#!/usr/bin/env node
// Generates the API types and spec metadata from ../api/openapi.yaml.
// `--check` regenerates in memory and fails when the committed files differ,
// so CI detects a spec change that was not followed by `npm run codegen`.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

const specUrl = new URL("../../api/openapi.yaml", import.meta.url);
const outputs = {
  schema: new URL("../src/shared/api/schema.gen.ts", import.meta.url),
  spec: new URL("../src/shared/api/spec.gen.ts", import.meta.url),
};
const banner = "// Generated by `npm run codegen` from api/openapi.yaml. Do not edit.\n";

async function generateSchema() {
  const ast = await openapiTS(specUrl, { alphabetize: false });
  return banner + "/* eslint-disable */\n" + astToString(ast);
}

async function generateSpecMetadata() {
  const spec = parse(await readFile(specUrl, "utf8"));
  const spa = spec["x-spa-routes"];
  const codes = spec.components["x-error-codes"];
  if (!spa || !Array.isArray(spa.routes) || !codes) {
    throw new Error("api/openapi.yaml lacks x-spa-routes or x-error-codes");
  }
  const errorCodes = Object.fromEntries(
    Object.entries(codes).map(([code, entry]) => [
      code,
      { status: entry.status, retryable: entry.retryable },
    ]),
  );
  const json = (value) => JSON.stringify(value, null, 2);
  return (
    banner +
    `\nexport const spaRoutes = ${json(spa.routes)} as const;\n` +
    `\nexport const spaAllowedQuery = ${json(spa.allowed_query ?? [])} as const;\n` +
    `\nexport const spaDocuments = ${json(spa.documents ?? {})} as const;\n` +
    `\nexport const errorCatalog = ${json(errorCodes)} as const;\n` +
    "\nexport type CatalogErrorCode = keyof typeof errorCatalog;\n"
  );
}

const generated = {
  schema: await generateSchema(),
  spec: await generateSpecMetadata(),
};
const check = process.argv.includes("--check");
let stale = false;
for (const [name, contents] of Object.entries(generated)) {
  const target = outputs[name];
  if (check) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== contents) {
      stale = true;
      console.error(`${fileURLToPath(target)} is out of date; run npm run codegen`);
    }
  } else {
    await writeFile(target, contents);
  }
}
if (stale) process.exit(1);
