import {mount,flushPromises} from "@vue/test-utils";
import {beforeEach,afterEach,expect,it,vi} from "vitest";
import CategoriesPage from "./CategoriesPage.vue";
import {configurationFixture,resetStores,response} from "../testSupport";
import {signedIn} from "../session";
import {setLanguage} from "../i18n";
beforeEach(()=>{resetStores();signedIn.value=true});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();setLanguage("en");document.body.innerHTML=""});
it("renames categories with same-value overrides, keeps a conflict draft and offers no create or delete",async()=>{
 let revision=4,conflict=true;
 const item=()=>({...configurationFixture({name:{en:"Tools","zh-CN":"工具"}},revision,"categories:tools"),kind:"categories",id:"tools",name:{en:"Tools","zh-CN":"工具"},builtin:true,applications:3});
 const fetch=vi.fn(async (url:string,init?:RequestInit)=>{if(init?.method==="PATCH"){if(conflict){revision=5;return response({error:{code:"DIRECTORY_REVISION_CONFLICT"}},409)}revision++;return response(item())}expect(url).toContain("/admin/api/categories");return response({items:[item()],page:1,total:1,total_pages:1,limit:25})});vi.stubGlobal("fetch",fetch);
 const wrapper=mount(CategoriesPage);await flushPromises();
 expect(wrapper.get(".directory-row").text()).toContain("3 applications");
 expect(wrapper.find('[aria-label="Create"]').exists()).toBe(false);expect(wrapper.find('[aria-label="Delete"]').exists()).toBe(false);expect(wrapper.find('[role="tab"]').exists()).toBe(false);
 await wrapper.get(".directory-row button").trigger("click");
 expect(wrapper.find(".field-reset").exists()).toBe(false);
 await wrapper.findAll("form.panel input")[0]!.setValue("Tools");await wrapper.get("form.panel").trigger("submit");await flushPromises();
 expect((wrapper.findAll("form.panel input")[0]!.element as HTMLInputElement).value).toBe("Tools");expect(wrapper.find('[role="alert"]').text()).toContain("draft is preserved");
 vi.stubGlobal("confirm",vi.fn(()=>true));await wrapper.get('[aria-label="Reload"]').trigger("click");await flushPromises();await wrapper.findAll("form.panel input")[0]!.setValue("Tools");conflict=false;await wrapper.get("form.panel").trigger("submit");await flushPromises();const patches=fetch.mock.calls.filter(([,init])=>init?.method==="PATCH");expect(JSON.parse(patches[1]![1]!.body as string)).toEqual({revision:5,set:{"name.en":"Tools"},unset:[]});
 setLanguage("zh-CN");await flushPromises();expect(wrapper.text()).toContain("管理分类");expect(wrapper.text()).toContain("3 个应用");wrapper.unmount();
});
