import { flushPromises } from "@vue/test-utils";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { boot, mountPage, resetStores, response } from "../testSupport";
import { setLanguage } from "../i18n";
beforeEach(resetStores);
afterEach(() => { vi.unstubAllGlobals(); setLanguage("en"); document.body.innerHTML=""; });
it("withholds vendor identity until loaded, clears it on navigation, ignores late metadata and retries errors", async () => {
  const pending = new Map<string, (result: ReturnType<typeof response>) => void>();
  const fetch = vi.fn((url: string) => {
    if (url.startsWith("/api/vendors/")) return new Promise<ReturnType<typeof response>>((resolve) => pending.set(url, resolve));
    if (url.startsWith("/api/catalog")) return Promise.resolve(response({ items: [], page: 1, total: 0, total_pages: 1 }));
    return Promise.resolve(response(boot));
  });
  vi.stubGlobal("fetch", fetch);
  const { wrapper, router } = await mountPage("/openai");
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.find(".breadcrumbs").exists()).toBe(false);
  expect(wrapper.find(".entity-icon").exists()).toBe(false);
  expect(wrapper.find(".empty").exists()).toBe(false);
  expect(wrapper.find('[role="status"]').exists()).toBe(true);
  const old = pending.get("/api/vendors/openai")!;
  await router.push("/anthropic"); await flushPromises();
  old(response({ id: "openai", name: { en: "Old wrong vendor", "zh-CN": "旧厂商" }, description: { en: "Old data" }, icon: "/wrong.svg" }));
  await flushPromises();
  expect(wrapper.text()).not.toContain("Old wrong vendor");
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  pending.get("/api/vendors/anthropic")!(response({ id: "anthropic", name: { en: "Loaded vendor", "zh-CN": "真实厂商" }, description: { en: "Loaded description", "zh-CN": "真实说明" }, icon: "", localized_icons: { en: "/en.svg", "zh-CN": "/zh.svg" } }));
  await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("Loaded vendor");
  expect(wrapper.get(".vendor-public-heading img").attributes("src")).toBe("/en.svg");
  setLanguage("zh-CN"); await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("真实厂商");
  expect(wrapper.get(".vendor-public-heading img").attributes("src")).toBe("/zh.svg");
  expect(wrapper.find(".empty").exists()).toBe(true);
  await router.push("/missing"); await flushPromises();
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.text()).not.toContain("真实厂商");
  pending.get("/api/vendors/missing")!(response({ error: { code: "NOT_FOUND" } }, 404)); await flushPromises();
  expect(wrapper.find('[role="alert"]').exists()).toBe(true);
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.find(".empty").exists()).toBe(false);
  await wrapper.get('[role="alert"] button').trigger("click"); await flushPromises();
  pending.get("/api/vendors/missing")!(response({ error: { code: "INTERNAL_ERROR" } }, 503)); await flushPromises();
  expect(wrapper.find('[role="alert"]').exists()).toBe(true);
  await wrapper.get('[role="alert"] button').trigger("click"); await flushPromises();
  pending.get("/api/vendors/missing")!(response({ id: "missing", name: { en: "No logo", "zh-CN": "没有标志" }, description: { en: "", "zh-CN": "" }, icon: "" })); await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("没有标志");
  expect(wrapper.find(".vendor-public-heading .entity-icon").exists()).toBe(false);
  wrapper.unmount();
});
