import { flushPromises } from "@vue/test-utils";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { boot, mountPage, resetStores, response } from "../testSupport";
import { setLanguage } from "../i18n";
beforeEach(resetStores);
afterEach(() => { vi.unstubAllGlobals(); setLanguage("en"); document.body.innerHTML=""; });
it("withholds vendor identity until loaded, clears it on navigation, ignores late metadata and retries errors", async () => {
  const pending = new Map<string, (result: ReturnType<typeof response>) => void>();
  const fetch = vi.fn((url: string) => {
    if (url.startsWith("/api/vendors/")) return new Promise<ReturnType<typeof response>>((resolve) => pending.set(url, resolve));
    if (url.startsWith("/api/catalog")) return Promise.resolve(response({ items: [], page: 1, total: 0, total_pages: 1 }));
    return Promise.resolve(response(boot));
  });
  vi.stubGlobal("fetch", fetch);
  const { wrapper, router } = await mountPage("/openai");
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.find(".breadcrumbs").exists()).toBe(false);
  expect(wrapper.find(".entity-icon").exists()).toBe(false);
  expect(wrapper.find(".empty").exists()).toBe(false);
  expect(wrapper.find('[role="status"]').exists()).toBe(true);
  const old = pending.get("/api/vendors/openai")!;
  await router.push("/anthropic"); await flushPromises();
  old(response({ id: "openai", name: { en: "Old wrong vendor", "zh-CN": "旧厂商" }, description: { en: "Old data" }, icon: "/wrong.svg" }));
  await flushPromises();
  expect(wrapper.text()).not.toContain("Old wrong vendor");
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  pending.get("/api/vendors/anthropic")!(response({ id: "anthropic", name: { en: "Loaded vendor", "zh-CN": "真实厂商" }, description: { en: "Loaded description", "zh-CN": "真实说明" }, icon: "", localized_icons: { en: "/en.svg", "zh-CN": "/zh.svg" } }));
  await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("Loaded vendor");
  expect(wrapper.get(".vendor-public-heading img").attributes("src")).toBe("/en.svg");
  expect(wrapper.get(".vendor-public-heading .entity-icon").attributes("style")).toContain("height: 48px");
  expect(wrapper.get(".public-search .search-input-icon").attributes("aria-hidden")).toBe("true");
  expect(wrapper.get(".public-search input").attributes("aria-label")).toBe("Search vendors and applications");
  setLanguage("zh-CN"); await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("真实厂商");
  expect(wrapper.get(".vendor-public-heading img").attributes("src")).toBe("/zh.svg");
  expect(wrapper.find(".empty").exists()).toBe(true);
  await router.push("/missing"); await flushPromises();
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.text()).not.toContain("真实厂商");
  pending.get("/api/vendors/missing")!(response({ error: { code: "NOT_FOUND" } }, 404)); await flushPromises();
  expect(wrapper.find('[role="alert"]').exists()).toBe(true);
  expect(wrapper.find(".vendor-public-heading").exists()).toBe(false);
  expect(wrapper.find(".empty").exists()).toBe(false);
  await wrapper.get('[role="alert"] button').trigger("click"); await flushPromises();
  pending.get("/api/vendors/missing")!(response({ error: { code: "INTERNAL_ERROR" } }, 503)); await flushPromises();
  expect(wrapper.find('[role="alert"]').exists()).toBe(true);
  await wrapper.get('[role="alert"] button').trigger("click"); await flushPromises();
  pending.get("/api/vendors/missing")!(response({ id: "missing", name: { en: "No logo", "zh-CN": "没有标志" }, description: { en: "", "zh-CN": "" }, icon: "" })); await flushPromises();
  expect(wrapper.get(".vendor-public-heading h1").text()).toBe("没有标志");
  expect(wrapper.find(".vendor-public-heading .entity-icon").exists()).toBe(false);
  wrapper.unmount();
});

it("composes category with search and page URLs and restores it on back navigation", async()=>{
 const fetch=vi.fn(async(url:string)=>response(url.startsWith('/api/catalog')?{items:[],page:Number(new URL(url,'http://local').searchParams.get('page')||1),total:50,total_pages:3,categories:[{id:'tools',name:{en:'Tools','zh-CN':'工具'}}]}:boot));vi.stubGlobal('fetch',fetch);
 const {wrapper,router}=await mountPage('/all?category=tools&q=cli&page=2');
 expect(fetch.mock.calls.some(([url])=>url.includes('category=tools')&&url.includes('q=cli')&&url.includes('page=2'))).toBe(true);
 setLanguage('zh-CN');await flushPromises();expect(wrapper.get('[role="combobox"][aria-label="分类"]').text()).toContain('工具');setLanguage('en');await flushPromises();
 await wrapper.get('[aria-label="Next page"]').trigger('click');await flushPromises();expect(router.currentRoute.value.query).toEqual({category:'tools',q:'cli',page:'3'});
 await wrapper.get('[role="combobox"][aria-label="Category"]').trigger('click');await wrapper.get('[role="option"][data-value=""]').trigger('click');await flushPromises();expect(router.currentRoute.value.query).toEqual({q:'cli'});
 router.back();await flushPromises();await flushPromises();expect(router.currentRoute.value.query.category).toBe('tools');expect(wrapper.get('[role="combobox"][aria-label="Category"]').text()).toContain('Tools');wrapper.unmount();
});
