package store

import (
	"context"
	"database/sql"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"
)

// Golden schema fixtures are SQL dumps of a populated data directory, one per
// schema version, in testdata/schema/v<N>.sql. The fixture of the current
// version is regenerated with
//
//	go test ./internal/store -run TestSchemaFixtureOfCurrentVersion -update-schema-fixture
//
// and committed whenever SchemaVersion changes. Older fixtures stay: from 1.0
// on they are the "from" databases every migration is tested against.
var updateSchemaFixture = flag.Bool("update-schema-fixture", false, "regenerate testdata/schema/v<SchemaVersion>.sql")

var fixtureName = regexp.MustCompile(`^v([0-9]+)\.sql$`)

func fixturePath(version int) string {
	return filepath.Join("testdata", "schema", fmt.Sprintf("v%d.sql", version))
}

// populateFixture writes one row of the main record kinds through the store API.
func populateFixture(t *testing.T, s *Store) {
	t.Helper()
	storage := storageOf(t, s, "fixture-vendor/fixture-app")
	r := releaseFixture(t, s, storage, "1.2.3")
	now := time.Date(2030, 1, 2, 3, 4, 5, 0, time.UTC)
	if err := s.PutChannel(Channel{AppID: r.AppID, Name: "latest", Version: r.Version, FetchedAt: now, ExpiresAt: now.Add(time.Hour)}); err != nil {
		t.Fatal(err)
	}
	if _, err := s.SaveSiteSettings(1, map[string]string{"title": "Fixture"}); err != nil {
		t.Fatal(err)
	}
	if err := s.AddFor(metricsOf(t, s, "fixture-vendor/fixture-app"), "requests", 3); err != nil {
		t.Fatal(err)
	}
}

// dumpDatabase writes a database as SQL that loadSchemaFixture replays: header
// pragmas, then each table followed by its rows, then indexes, views and
// triggers, so that triggers do not fire while rows are loaded.
func dumpDatabase(t *testing.T, path string) string {
	t.Helper()
	db, err := sql.Open("sqlite3", sqliteURL(path, "mode=ro"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	app, version, err := readHeader(context.Background(), db)
	if err != nil {
		t.Fatal(err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Schema %d fixture. Generated by\n-- go test ./internal/store -run TestSchemaFixtureOfCurrentVersion -update-schema-fixture\n", version)
	fmt.Fprintf(&b, "PRAGMA application_id=%d;\nPRAGMA user_version=%d;\n", app, version)
	query := func(q string, args ...any) [][]string {
		rows, err := db.Query(q, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()
		columns, _ := rows.Columns()
		var out [][]string
		for rows.Next() {
			values := make([]string, len(columns))
			pointers := make([]any, len(columns))
			for i := range values {
				pointers[i] = &values[i]
			}
			if err = rows.Scan(pointers...); err != nil {
				t.Fatal(err)
			}
			out = append(out, values)
		}
		if err = rows.Err(); err != nil {
			t.Fatal(err)
		}
		return out
	}
	for _, table := range query(`SELECT name, sql FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite\_%' ESCAPE '\' ORDER BY name`) {
		b.WriteString(table[1] + ";\n")
		var columns, quoted []string
		for _, column := range query(`SELECT name FROM pragma_table_info(?) ORDER BY cid`, table[0]) {
			columns = append(columns, strconv.Quote(column[0]))
			quoted = append(quoted, "quote("+strconv.Quote(column[0])+")")
		}
		for _, row := range query(`SELECT ` + strings.Join(quoted, ` || ',' || `) + ` FROM ` + strconv.Quote(table[0]) + ` ORDER BY rowid`) {
			fmt.Fprintf(&b, "INSERT INTO %s(%s) VALUES(%s);\n", strconv.Quote(table[0]), strings.Join(columns, ","), row[0])
		}
	}
	for _, object := range query(`SELECT sql FROM sqlite_schema WHERE type IN ('index','view','trigger') AND sql IS NOT NULL ORDER BY type='trigger', type, name`) {
		b.WriteString(object[0] + ";\n")
	}
	return b.String()
}

// loadSchemaFixture writes the fixture into dir as a closed, checkpointed WAL
// database, as a stopped RedApp of that version leaves it.
func loadSchemaFixture(t *testing.T, dir, file string) string {
	t.Helper()
	dump, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, databaseName)
	db, err := sql.Open("sqlite3", sqliteURL(path, "mode=rwc&_journal_mode=WAL"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	db.SetMaxOpenConns(1)
	tx, err := db.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	if _, err = tx.Exec(string(dump)); err != nil {
		t.Fatalf("load %s: %v", file, err)
	}
	if err = tx.Commit(); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestSchemaFixtureOfCurrentVersion(t *testing.T) {
	file := fixturePath(SchemaVersion)
	if *updateSchemaFixture {
		dir := t.TempDir()
		s, err := Open(dir)
		if err != nil {
			t.Fatal(err)
		}
		populateFixture(t, s)
		if err = s.Close(); err != nil {
			t.Fatal(err)
		}
		if err = os.MkdirAll(filepath.Dir(file), 0755); err != nil {
			t.Fatal(err)
		}
		if err = os.WriteFile(file, []byte(dumpDatabase(t, filepath.Join(dir, databaseName))), 0644); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := os.Stat(file); err != nil {
		t.Fatalf("schema %d has no golden fixture; generate it with -update-schema-fixture: %v", SchemaVersion, err)
	}
	dir := t.TempDir()
	path := loadSchemaFixture(t, dir, file)
	want, err := freshSchemaObjects(context.Background(), schema)
	if err != nil {
		t.Fatal(err)
	}
	if got := objectsOf(t, path); !reflect.DeepEqual(got, want) {
		t.Fatalf("%s does not match schema.sql; a schema change needs a new SchemaVersion and fixture", file)
	}
	// A fresh directory created by Open has the same schema as schema.sql.
	fresh := openTest(t)
	if got, err := schemaObjects(context.Background(), fresh.read); err != nil || !reflect.DeepEqual(got, want) {
		t.Fatalf("fresh database schema differs from schema.sql: %v", err)
	}
	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open on the current fixture: %v", err)
	}
	defer s.Close()
	if _, err = s.Application("fixture-vendor/fixture-app"); err != nil {
		t.Fatalf("fixture application: %v", err)
	}
}

// Every fixture of an older version is either migrated by the production plan
// to a schema identical to a fresh one, or refused without modification
// (before 1.0, and below MinimumMigratableVersion afterwards).
func TestSchemaFixturesOfOlderVersions(t *testing.T) {
	entries, err := os.ReadDir(filepath.Join("testdata", "schema"))
	if err != nil {
		t.Fatal(err)
	}
	plan := productionPlan()
	for _, entry := range entries {
		match := fixtureName.FindStringSubmatch(entry.Name())
		if match == nil {
			t.Errorf("unexpected file testdata/schema/%s", entry.Name())
			continue
		}
		version, _ := strconv.Atoi(match[1])
		if version == SchemaVersion {
			continue
		}
		t.Run(entry.Name(), func(t *testing.T) {
			dir := t.TempDir()
			loadSchemaFixture(t, dir, filepath.Join("testdata", "schema", entry.Name()))
			upgrade, refusal := plan.classify(applicationID, version)
			before := snapshotFiles(t, dir)
			s, err := Open(dir)
			if !upgrade {
				if err == nil {
					s.Close()
				}
				if !errors.Is(err, ErrIncompatibleDirectory) || refusal == nil {
					t.Fatalf("Open = %v; want refusal", err)
				}
				if after := snapshotFiles(t, dir); !reflect.DeepEqual(before, after) {
					t.Fatal("refusal changed the data directory")
				}
				return
			}
			if err != nil {
				t.Fatalf("migrate schema %d fixture: %v", version, err)
			}
			defer s.Close()
			got, err := schemaObjects(context.Background(), s.read)
			if err != nil {
				t.Fatal(err)
			}
			want, err := freshSchemaObjects(context.Background(), schema)
			if err != nil || !reflect.DeepEqual(got, want) {
				t.Fatalf("migrated schema differs from a fresh schema: %v", err)
			}
			if _, err = s.Application("fixture-vendor/fixture-app"); err != nil {
				t.Fatalf("fixture application after migration: %v", err)
			}
		})
	}
}
